name: post-400-status-test

on:
  # schedule trigger
  schedule:
    # Every Sunday at 15:00 (UTC, JST: 0:00)
    - cron: '0 15 * * 0'

jobs:
  call-testing-workflow:
    name: Call Testing Workflow
    uses: ./.github/workflows/_common_testing_workflow.yml
    with:
      testfilename: post-400-status-test